/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biometricauth.guis;

import biometricauth.controllers.AuthController;
import biometricauth.controllers.UserController;
import biometricauth.models.HandGeometry;
import com.mysql.jdbc.StringUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author Max
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtIndexFingerHeight = new javax.swing.JTextField();
        txtMiddleFingerHeight = new javax.swing.JTextField();
        txtRingFingerHeight = new javax.swing.JTextField();
        txtPalmAcrossLength = new javax.swing.JTextField();
        txtPalmHeight = new javax.swing.JTextField();
        txtPinkyHeight = new javax.swing.JTextField();
        btnSignIn = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sign In"));

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        jLabel4.setText("Index Finger Height");

        jLabel5.setText("Middle Finger Height");

        jLabel6.setText("Ring Finger Height");

        jLabel7.setText("Pinky Height");

        jLabel8.setText("Palm Across Length");

        jLabel9.setText("Palm height");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtIndexFingerHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIndexFingerHeightActionPerformed(evt);
            }
        });

        txtMiddleFingerHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiddleFingerHeightActionPerformed(evt);
            }
        });

        txtRingFingerHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRingFingerHeightActionPerformed(evt);
            }
        });

        txtPalmAcrossLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPalmAcrossLengthActionPerformed(evt);
            }
        });

        txtPalmHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPalmHeightActionPerformed(evt);
            }
        });

        txtPinkyHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPinkyHeightActionPerformed(evt);
            }
        });

        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPalmHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtPalmAcrossLength, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtRingFingerHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtMiddleFingerHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtIndexFingerHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtPinkyHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtPassword))))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignIn)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIndexFingerHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMiddleFingerHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRingFingerHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPinkyHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPalmAcrossLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPalmHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignIn)
                    .addComponent(btnClear))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtMiddleFingerHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiddleFingerHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiddleFingerHeightActionPerformed

    private void txtRingFingerHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRingFingerHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRingFingerHeightActionPerformed

    private void txtPalmAcrossLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPalmAcrossLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPalmAcrossLengthActionPerformed

    private void txtPalmHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPalmHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPalmHeightActionPerformed

    private void txtPinkyHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPinkyHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinkyHeightActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        boolean authenticated = true;
        String username = txtUsername.getText().trim();
        String password = txtPassword.getText().trim();

        String indexFingerHeight = txtIndexFingerHeight.getText().trim();
        String middleFingerHeight = txtMiddleFingerHeight.getText().trim();
        String ringFingerHeight = txtRingFingerHeight.getText().trim();
        String pinkyHeight = txtPinkyHeight.getText().trim();
        String palmAcrossLength = txtPalmAcrossLength.getText().trim();
        String palmHeight = txtPalmHeight.getText().trim();

        // Input Validation
        if (StringUtils.isEmptyOrWhitespaceOnly(username)
                || StringUtils.isEmptyOrWhitespaceOnly(password)
                || StringUtils.isEmptyOrWhitespaceOnly(indexFingerHeight)
                || StringUtils.isEmptyOrWhitespaceOnly(middleFingerHeight)
                || StringUtils.isEmptyOrWhitespaceOnly(ringFingerHeight)
                || StringUtils.isEmptyOrWhitespaceOnly(pinkyHeight)
                || StringUtils.isEmptyOrWhitespaceOnly(palmAcrossLength)
                || StringUtils.isEmptyOrWhitespaceOnly(palmHeight)) {
            JOptionPane.showMessageDialog(this, "Fill in all the fields");
            return;
        }

        if (password.length() < 4) {
            JOptionPane.showMessageDialog(this, "Password should contain at least 4 characters");
            authenticated = false;
            return;
        }

        // Check if the user is registered
        if (AuthController.usernameExists(username)) {
            if (!AuthController.matchUsernamePassword(username, password)){
                JOptionPane.showMessageDialog(this, "Username and Password does not match");
                authenticated = false;
                return;
            }
            
            // username and password matches at this point
        } else {
            JOptionPane.showMessageDialog(this, "Username not recognized");
            return;
        }

        // check HandGeometry deviation, now that the username and password match is complete
        HandGeometry entered = new HandGeometry(indexFingerHeight, middleFingerHeight, ringFingerHeight, pinkyHeight, palmAcrossLength, palmHeight);
        HandGeometry stored = UserController.getHandGeometryOfUser(username);
        double deviation = AuthController.getHandGeometryMatchScore(entered, stored);

        if (deviation > 10) {
            // Deviation too high to authenticate
            authenticated = false;
        }

        if (authenticated) {
            this.dispose();
            Dashboard d = new Dashboard();
            d.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Hand Geometry Authentication Failed");
        }

    }//GEN-LAST:event_btnSignInActionPerformed
    // end of btnSignInActionPerformed()

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtIndexFingerHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIndexFingerHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIndexFingerHeightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    private void clear() {
        txtUsername.setText("");
        txtPassword.setText("");
        txtIndexFingerHeight.setText("");
        txtMiddleFingerHeight.setText("");
        txtRingFingerHeight.setText("");
        txtPalmAcrossLength.setText("");
        txtPalmHeight.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIndexFingerHeight;
    private javax.swing.JTextField txtMiddleFingerHeight;
    private javax.swing.JTextField txtPalmAcrossLength;
    private javax.swing.JTextField txtPalmHeight;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPinkyHeight;
    private javax.swing.JTextField txtRingFingerHeight;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
